# Generated by Django 2.0.13 on 2019-04-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_comment_commentlike_commentunlike_reply_videolike_videounlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
