# Generated by Django 2.0.13 on 2019-04-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
    ]
