# Generated by Django 2.0.13 on 2019-04-06 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to=settings.AUTH_USER_MODEL),
        ),
    ]
