# Generated by Django 2.0.13 on 2019-04-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190406_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='stream_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
