# Generated by Django 2.0.13 on 2019-04-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_channel_stream_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_streaming',
            field=models.BooleanField(default=False),
        ),
    ]
