# Generated by Django 2.0.13 on 2019-05-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_is_streaming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
